file:
  upload-dir:
    audio: E:\代码\学校\毕业设计\Let's Goplay\upload\
    image:
      playlist-cover: E:\代码\学校\毕业设计\Let's Goplay\upload\image\playlist-cover\
      user-avatar: E:\代码\学校\毕业设计\Let's Goplay\upload\image\user-avatar\
      post-img: E:\代码\学校\毕业设计\Let's Goplay\upload\image\post-img\